#+TITLE: Mini Jenkins with Bash

** What is it?
mj5s.sh is a Bash script designed to automate various tasks related to managing multiple Git repositories. It provides a set of functions to simplify tasks like cloning repositories, fetching updates, checking out branches, pushing changes, building JAR files, creating Docker images, and more.

** How does it work?
*** Urls
#+BEGIN_SRC shell
__urls=(
  git@github.com:Noman5237/repo-test-1.git
  git@github.com:Noman5237/repo-test-2.git
)
#+END_SRC

The __urls array stores the Git repository URLs that you want to manage using this script. You can add or modify repository URLs in this array to suit your needs.
*** Functions
The script defines various functions to perform tasks on Git repositories. These functions include:

*The function names that begins with underscores only executes once and other functions gets executed for all repositories.*

- *_service*: Filters and selects repositories based on provided arguments like only and except.
- *clone*: Clones Git repositories or updates them if they already exist.
- *fetch*: Fetches updates from remote repositories.
- *checkout*: Checks out a specific branch in each repository.
- *remote*: Configures or updates Git remotes.
- *merge*: Merges a specified branch in each repository.
- *pull*: Pulls changes from a remote branch.
- *tag*: Tags a specific branch in each repository.
- *push*: Pushes changes to a remote branch.
- *mvnw_permission*: Changes the executable permission for the mvnw script.
- *jar*: Cleans and builds a JAR file for each repository.
- *image*: Builds a Docker image for each repository.
- *_registry*: Logs in to a Docker registry using provided credentials.
- *image_push*: Pushes a Docker image to a registry.

You can execute these functions in conjunction with various arguments to perform specific actions on the repositories.

The functions takes arguments in form of *-key=value* format

** Examples
*** Pulling from a branch
#+BEGIN_SRC shell
./mj5s.sh pull -remote=gitea -branch=alpha
#+END_SRC
*** Pushing to a branch
#+BEGIN_SRC shell
./mj5s.sh push -remote=github -branch=alpha
#+END_SRC
*** Doing them together one after another
#+BEGIN_SRC shell
./mj5s.sh pull -remote=gitea -branch=alpha push -remote=github -branch=alpha
#+END_SRC
*** Creating Jars and Building images
#+BEGIN_SRC shell
# This will build jar files and create image except for repo-test-1
./mj5s.sh _service -except=repo-test-1 jar image -prefix=noman5237/prod -tag=2.0.0
# This will build jar files and create image only for repo-test-1
./mj5s.sh _service -only=repo-test-1 jar image -prefix=noman5237/prod -tag=2.0.0
#+END_SRC
***
